### ISSUE TITLE
Deployment on (non english server) localization issues?

### ISSUE THREAD

**Issue by meister-d** [vtfuture/BForms#238]
Hi Guys
we have deployed a solution based on  BForms  on a German localized server. Some of the Controls seems to be broken, and the Waiting indicator is allways turning. 

We have traced this behaviour with fiddler and have constated that there were some files missing:

As a Quick Fix we have created the corresponding files and have added them to the RequiresJS.json file.

```
"validate-de": "bforms/plugins/validation/i18n/bforms.validate-de",
"select2-de": "bforms/plugins/select2/js/i18n/select2-de",
```

It seems, that also the Datepicke gets broken if there are languages missing:
for this purpose I added a "fake" german counterpart ;-)

```
 $.fn.bsDatepickerLang = {
        'en': {
            nowText: 'Now',
            setDateText: 'Set date',
            setTimeText: 'Set time'
        },
        'ro': {
            nowText: 'Acum',
            setDateText: 'Setează data',
            setTimeText: 'Setează ora'
        },
        'de': {
            nowText: 'Now',
            setDateText: 'Set date',
            setTimeText: 'Set time'
        }
    };
```

What is the best way to do localisation with Bforms? 
Is it possible to configure a Timeout for the waiting indicator (in general for the Ajax operations)?

Regards Dumitru (aka Meister-D)

**Comment by mariuscosareanu** [comment]
* Hello @meister-d , that's the correct solution regarding the localization of the the select2/validation plugins, you have to add a path in your RequireJs.json config using the *plugin*-*lang* naming convention.

* For the datepicker you should load the 'bforms-datepicker' script before applying the plugin/ using bsInitUI on the form and add your resources to the `$.fn.bsDatepickerLang` object, without modifying the bforms.datepicker.js script, like this:

```javascript
$.fn.bsDatepickerLang['en'] = {
      nowText: 'Now',
            setDateText: 'Set date',
            setTimeText: 'Set time'
        };
```
* For server side localized resources you can use the `BForms.Utilities.BsResourceManager`. An example of usage can be found in the `Global.axas.cs` file from the` BForms.Docs` project.

* The waiting indicator wasn't removed because datepicker was throwing an error.Otherwise, the bsInitUI should handle that.
 But for ajax requests we added two new callbacks, `onTimeout` and `offline`.The `onTimeout` callback is used when an ajax request takes longer than the specified `timeout` option (in milliseconds), and the `offline` one when the user loses internet connection.You can use them to remove the waiting indicators added from your code and also notify the user.
